// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package com.tencent.mars.sample.chat.proto;

public final class Lock {
  private Lock() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LockResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tencent.mars.sample.chat.proto.LockResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 cabinetCode = 1;</code>
     */
    boolean hasCabinetCode();
    /**
     * <code>required int32 cabinetCode = 1;</code>
     */
    int getCabinetCode();

    /**
     * <code>required int32 boxCode = 2;</code>
     */
    boolean hasBoxCode();
    /**
     * <code>required int32 boxCode = 2;</code>
     */
    int getBoxCode();

    /**
     * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
     */
    boolean hasBoxSize();
    /**
     * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
     */
    com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize getBoxSize();

    /**
     * <code>required bool isOpen = 4;</code>
     */
    boolean hasIsOpen();
    /**
     * <code>required bool isOpen = 4;</code>
     */
    boolean getIsOpen();

    /**
     * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
     */
    com.tencent.mars.sample.chat.proto.Lock.GetLockRequest getRequest();
    /**
     * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
     */
    com.tencent.mars.sample.chat.proto.Lock.GetLockRequestOrBuilder getRequestOrBuilder();
  }
  /**
   * Protobuf type {@code com.tencent.mars.sample.chat.proto.LockResponse}
   */
  public static final class LockResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.tencent.mars.sample.chat.proto.LockResponse)
      LockResponseOrBuilder {
    // Use LockResponse.newBuilder() to construct.
    private LockResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LockResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LockResponse defaultInstance;
    public static LockResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LockResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LockResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cabinetCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              boxCode_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize value = com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                boxSize_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isOpen_ = input.readBool();
              break;
            }
            case 42: {
              com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_LockResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_LockResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.mars.sample.chat.proto.Lock.LockResponse.class, com.tencent.mars.sample.chat.proto.Lock.LockResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<LockResponse> PARSER =
        new com.google.protobuf.AbstractParser<LockResponse>() {
      public LockResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LockResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LockResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.tencent.mars.sample.chat.proto.LockResponse.BoxSize}
     */
    public enum BoxSize
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LARGE = 0;</code>
       */
      LARGE(0, 0),
      /**
       * <code>MIDEL = 1;</code>
       */
      MIDEL(1, 1),
      /**
       * <code>SMALL = 2;</code>
       */
      SMALL(2, 2),
      ;

      /**
       * <code>LARGE = 0;</code>
       */
      public static final int LARGE_VALUE = 0;
      /**
       * <code>MIDEL = 1;</code>
       */
      public static final int MIDEL_VALUE = 1;
      /**
       * <code>SMALL = 2;</code>
       */
      public static final int SMALL_VALUE = 2;


      public final int getNumber() { return value; }

      public static BoxSize valueOf(int value) {
        switch (value) {
          case 0: return LARGE;
          case 1: return MIDEL;
          case 2: return SMALL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BoxSize>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BoxSize>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BoxSize>() {
              public BoxSize findValueByNumber(int number) {
                return BoxSize.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tencent.mars.sample.chat.proto.Lock.LockResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final BoxSize[] VALUES = values();

      public static BoxSize valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BoxSize(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.tencent.mars.sample.chat.proto.LockResponse.BoxSize)
    }

    private int bitField0_;
    public static final int CABINETCODE_FIELD_NUMBER = 1;
    private int cabinetCode_;
    /**
     * <code>required int32 cabinetCode = 1;</code>
     */
    public boolean hasCabinetCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cabinetCode = 1;</code>
     */
    public int getCabinetCode() {
      return cabinetCode_;
    }

    public static final int BOXCODE_FIELD_NUMBER = 2;
    private int boxCode_;
    /**
     * <code>required int32 boxCode = 2;</code>
     */
    public boolean hasBoxCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 boxCode = 2;</code>
     */
    public int getBoxCode() {
      return boxCode_;
    }

    public static final int BOXSIZE_FIELD_NUMBER = 3;
    private com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize boxSize_;
    /**
     * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
     */
    public boolean hasBoxSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
     */
    public com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize getBoxSize() {
      return boxSize_;
    }

    public static final int ISOPEN_FIELD_NUMBER = 4;
    private boolean isOpen_;
    /**
     * <code>required bool isOpen = 4;</code>
     */
    public boolean hasIsOpen() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool isOpen = 4;</code>
     */
    public boolean getIsOpen() {
      return isOpen_;
    }

    public static final int REQUEST_FIELD_NUMBER = 5;
    private com.tencent.mars.sample.chat.proto.Lock.GetLockRequest request_;
    /**
     * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
     */
    public com.tencent.mars.sample.chat.proto.Lock.GetLockRequest getRequest() {
      return request_;
    }
    /**
     * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
     */
    public com.tencent.mars.sample.chat.proto.Lock.GetLockRequestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    private void initFields() {
      cabinetCode_ = 0;
      boxCode_ = 0;
      boxSize_ = com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize.LARGE;
      isOpen_ = false;
      request_ = com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCabinetCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBoxCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBoxSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cabinetCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, boxCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, boxSize_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isOpen_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, request_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cabinetCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, boxCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, boxSize_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isOpen_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, request_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.LockResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tencent.mars.sample.chat.proto.Lock.LockResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tencent.mars.sample.chat.proto.LockResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tencent.mars.sample.chat.proto.LockResponse)
        com.tencent.mars.sample.chat.proto.Lock.LockResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_LockResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_LockResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.mars.sample.chat.proto.Lock.LockResponse.class, com.tencent.mars.sample.chat.proto.Lock.LockResponse.Builder.class);
      }

      // Construct using com.tencent.mars.sample.chat.proto.Lock.LockResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cabinetCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        boxCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        boxSize_ = com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize.LARGE;
        bitField0_ = (bitField0_ & ~0x00000004);
        isOpen_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (requestBuilder_ == null) {
          request_ = com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_LockResponse_descriptor;
      }

      public com.tencent.mars.sample.chat.proto.Lock.LockResponse getDefaultInstanceForType() {
        return com.tencent.mars.sample.chat.proto.Lock.LockResponse.getDefaultInstance();
      }

      public com.tencent.mars.sample.chat.proto.Lock.LockResponse build() {
        com.tencent.mars.sample.chat.proto.Lock.LockResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.mars.sample.chat.proto.Lock.LockResponse buildPartial() {
        com.tencent.mars.sample.chat.proto.Lock.LockResponse result = new com.tencent.mars.sample.chat.proto.Lock.LockResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cabinetCode_ = cabinetCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.boxCode_ = boxCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.boxSize_ = boxSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isOpen_ = isOpen_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.mars.sample.chat.proto.Lock.LockResponse) {
          return mergeFrom((com.tencent.mars.sample.chat.proto.Lock.LockResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.mars.sample.chat.proto.Lock.LockResponse other) {
        if (other == com.tencent.mars.sample.chat.proto.Lock.LockResponse.getDefaultInstance()) return this;
        if (other.hasCabinetCode()) {
          setCabinetCode(other.getCabinetCode());
        }
        if (other.hasBoxCode()) {
          setBoxCode(other.getBoxCode());
        }
        if (other.hasBoxSize()) {
          setBoxSize(other.getBoxSize());
        }
        if (other.hasIsOpen()) {
          setIsOpen(other.getIsOpen());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCabinetCode()) {
          
          return false;
        }
        if (!hasBoxCode()) {
          
          return false;
        }
        if (!hasBoxSize()) {
          
          return false;
        }
        if (!hasIsOpen()) {
          
          return false;
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.mars.sample.chat.proto.Lock.LockResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.mars.sample.chat.proto.Lock.LockResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cabinetCode_ ;
      /**
       * <code>required int32 cabinetCode = 1;</code>
       */
      public boolean hasCabinetCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cabinetCode = 1;</code>
       */
      public int getCabinetCode() {
        return cabinetCode_;
      }
      /**
       * <code>required int32 cabinetCode = 1;</code>
       */
      public Builder setCabinetCode(int value) {
        bitField0_ |= 0x00000001;
        cabinetCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cabinetCode = 1;</code>
       */
      public Builder clearCabinetCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cabinetCode_ = 0;
        onChanged();
        return this;
      }

      private int boxCode_ ;
      /**
       * <code>required int32 boxCode = 2;</code>
       */
      public boolean hasBoxCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 boxCode = 2;</code>
       */
      public int getBoxCode() {
        return boxCode_;
      }
      /**
       * <code>required int32 boxCode = 2;</code>
       */
      public Builder setBoxCode(int value) {
        bitField0_ |= 0x00000002;
        boxCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 boxCode = 2;</code>
       */
      public Builder clearBoxCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        boxCode_ = 0;
        onChanged();
        return this;
      }

      private com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize boxSize_ = com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize.LARGE;
      /**
       * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
       */
      public boolean hasBoxSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
       */
      public com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize getBoxSize() {
        return boxSize_;
      }
      /**
       * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
       */
      public Builder setBoxSize(com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        boxSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.tencent.mars.sample.chat.proto.LockResponse.BoxSize boxSize = 3;</code>
       */
      public Builder clearBoxSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        boxSize_ = com.tencent.mars.sample.chat.proto.Lock.LockResponse.BoxSize.LARGE;
        onChanged();
        return this;
      }

      private boolean isOpen_ ;
      /**
       * <code>required bool isOpen = 4;</code>
       */
      public boolean hasIsOpen() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool isOpen = 4;</code>
       */
      public boolean getIsOpen() {
        return isOpen_;
      }
      /**
       * <code>required bool isOpen = 4;</code>
       */
      public Builder setIsOpen(boolean value) {
        bitField0_ |= 0x00000008;
        isOpen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isOpen = 4;</code>
       */
      public Builder clearIsOpen() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isOpen_ = false;
        onChanged();
        return this;
      }

      private com.tencent.mars.sample.chat.proto.Lock.GetLockRequest request_ = com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.tencent.mars.sample.chat.proto.Lock.GetLockRequest, com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder, com.tencent.mars.sample.chat.proto.Lock.GetLockRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public com.tencent.mars.sample.chat.proto.Lock.GetLockRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public Builder setRequest(com.tencent.mars.sample.chat.proto.Lock.GetLockRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public Builder setRequest(
          com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public Builder mergeRequest(com.tencent.mars.sample.chat.proto.Lock.GetLockRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              request_ != com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.getDefaultInstance()) {
            request_ =
              com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      public com.tencent.mars.sample.chat.proto.Lock.GetLockRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .com.tencent.mars.sample.chat.proto.GetLockRequest request = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.tencent.mars.sample.chat.proto.Lock.GetLockRequest, com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder, com.tencent.mars.sample.chat.proto.Lock.GetLockRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tencent.mars.sample.chat.proto.Lock.GetLockRequest, com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder, com.tencent.mars.sample.chat.proto.Lock.GetLockRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.tencent.mars.sample.chat.proto.LockResponse)
    }

    static {
      defaultInstance = new LockResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.chat.proto.LockResponse)
  }

  public interface GetLockRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tencent.mars.sample.chat.proto.GetLockRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sn = 1;</code>
     */
    boolean hasSn();
    /**
     * <code>required string sn = 1;</code>
     */
    java.lang.String getSn();
    /**
     * <code>required string sn = 1;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    /**
     * <code>optional string address = 2;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 2;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.tencent.mars.sample.chat.proto.GetLockRequest}
   */
  public static final class GetLockRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.tencent.mars.sample.chat.proto.GetLockRequest)
      GetLockRequestOrBuilder {
    // Use GetLockRequest.newBuilder() to construct.
    private GetLockRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetLockRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetLockRequest defaultInstance;
    public static GetLockRequest getDefaultInstance() {
      return defaultInstance;
    }

    public GetLockRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetLockRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sn_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              address_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.class, com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<GetLockRequest> PARSER =
        new com.google.protobuf.AbstractParser<GetLockRequest>() {
      public GetLockRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetLockRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetLockRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SN_FIELD_NUMBER = 1;
    private java.lang.Object sn_;
    /**
     * <code>required string sn = 1;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sn = 1;</code>
     */
    public java.lang.String getSn() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sn = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 2;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sn_ = "";
      address_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAddressBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAddressBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tencent.mars.sample.chat.proto.Lock.GetLockRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tencent.mars.sample.chat.proto.GetLockRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tencent.mars.sample.chat.proto.GetLockRequest)
        com.tencent.mars.sample.chat.proto.Lock.GetLockRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.class, com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.Builder.class);
      }

      // Construct using com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sn_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.mars.sample.chat.proto.Lock.internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_descriptor;
      }

      public com.tencent.mars.sample.chat.proto.Lock.GetLockRequest getDefaultInstanceForType() {
        return com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.getDefaultInstance();
      }

      public com.tencent.mars.sample.chat.proto.Lock.GetLockRequest build() {
        com.tencent.mars.sample.chat.proto.Lock.GetLockRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.mars.sample.chat.proto.Lock.GetLockRequest buildPartial() {
        com.tencent.mars.sample.chat.proto.Lock.GetLockRequest result = new com.tencent.mars.sample.chat.proto.Lock.GetLockRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.mars.sample.chat.proto.Lock.GetLockRequest) {
          return mergeFrom((com.tencent.mars.sample.chat.proto.Lock.GetLockRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.mars.sample.chat.proto.Lock.GetLockRequest other) {
        if (other == com.tencent.mars.sample.chat.proto.Lock.GetLockRequest.getDefaultInstance()) return this;
        if (other.hasSn()) {
          bitField0_ |= 0x00000001;
          sn_ = other.sn_;
          onChanged();
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000002;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.mars.sample.chat.proto.Lock.GetLockRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.mars.sample.chat.proto.Lock.GetLockRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sn_ = "";
      /**
       * <code>required string sn = 1;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public java.lang.String getSn() {
        java.lang.Object ref = sn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        java.lang.Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public Builder setSn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 2;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 2;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tencent.mars.sample.chat.proto.GetLockRequest)
    }

    static {
      defaultInstance = new GetLockRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.chat.proto.GetLockRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tencent_mars_sample_chat_proto_LockResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tencent_mars_sample_chat_proto_LockResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nlock.proto\022\"com.tencent.mars.sample.ch" +
      "at.proto\"\200\002\n\014LockResponse\022\023\n\013cabinetCode" +
      "\030\001 \002(\005\022\017\n\007boxCode\030\002 \002(\005\022I\n\007boxSize\030\003 \002(\016" +
      "28.com.tencent.mars.sample.chat.proto.Lo" +
      "ckResponse.BoxSize\022\016\n\006isOpen\030\004 \002(\010\022C\n\007re" +
      "quest\030\005 \001(\01322.com.tencent.mars.sample.ch" +
      "at.proto.GetLockRequest\"*\n\007BoxSize\022\t\n\005LA" +
      "RGE\020\000\022\t\n\005MIDEL\020\001\022\t\n\005SMALL\020\002\"-\n\016GetLockRe" +
      "quest\022\n\n\002sn\030\001 \002(\t\022\017\n\007address\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tencent_mars_sample_chat_proto_LockResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tencent_mars_sample_chat_proto_LockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tencent_mars_sample_chat_proto_LockResponse_descriptor,
        new java.lang.String[] { "CabinetCode", "BoxCode", "BoxSize", "IsOpen", "Request", });
    internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tencent_mars_sample_chat_proto_GetLockRequest_descriptor,
        new java.lang.String[] { "Sn", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
